/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.app.fgsstarttesthelper;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.content.Intent;
import android.os.Parcel;
import android.os.Parcelable;

import com.android.internal.util.DataClass;

/**
 * Message class used in this test.
 */
@DataClass(
        genConstructor = false,
        genSetters = true,
        genToString = true,
        genAidl = false)
public class FgsNewLogicMessage implements Parcelable {
    public FgsNewLogicMessage() {
    }

    private boolean mFgsStarted;

    @Nullable
    private String mUnexpectedErrorMessage;

    public void setToIntent(Intent i) {
        i.putExtra(FgsNewLogicMessage.class.getName(), this);
    }

    public static FgsNewLogicMessage getFromIntent(Intent i) {
        return i.getParcelableExtra(FgsNewLogicMessage.class.getName(), FgsNewLogicMessage.class);
    }



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/cts/tests/app/FgsTestHelper/src/android/app/fgstesthelper/FgsNewLogicMessage.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public boolean isFgsStarted() {
        return mFgsStarted;
    }

    @DataClass.Generated.Member
    public @Nullable String getUnexpectedErrorMessage() {
        return mUnexpectedErrorMessage;
    }

    @DataClass.Generated.Member
    public @NonNull FgsNewLogicMessage setFgsStarted( boolean value) {
        mFgsStarted = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull FgsNewLogicMessage setUnexpectedErrorMessage(@NonNull String value) {
        mUnexpectedErrorMessage = value;
        return this;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "FgsNewLogicMessage { " +
                "fgsStarted = " + mFgsStarted + ", " +
                "unexpectedErrorMessage = " + mUnexpectedErrorMessage +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mFgsStarted) flg |= 0x1;
        if (mUnexpectedErrorMessage != null) flg |= 0x2;
        dest.writeByte(flg);
        if (mUnexpectedErrorMessage != null) dest.writeString(mUnexpectedErrorMessage);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected FgsNewLogicMessage(@NonNull Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        boolean fgsStarted = (flg & 0x1) != 0;
        String unexpectedErrorMessage = (flg & 0x2) == 0 ? null : in.readString();

        this.mFgsStarted = fgsStarted;
        this.mUnexpectedErrorMessage = unexpectedErrorMessage;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<FgsNewLogicMessage> CREATOR
            = new Parcelable.Creator<FgsNewLogicMessage>() {
        @Override
        public FgsNewLogicMessage[] newArray(int size) {
            return new FgsNewLogicMessage[size];
        }

        @Override
        public FgsNewLogicMessage createFromParcel(@NonNull Parcel in) {
            return new FgsNewLogicMessage(in);
        }
    };

    @DataClass.Generated(
            time = 1706052038855L,
            codegenVersion = "1.0.23",
            sourceFile = "cts/tests/app/FgsTestHelper/src/android/app/fgstesthelper/FgsNewLogicMessage.java",
            inputSignatures = "private  boolean mFgsStarted\nprivate @android.annotation.Nullable java.lang.String mUnexpectedErrorMessage\npublic  void setToIntent(android.content.Intent)\npublic static  android.app.fgstesthelper.FgsNewLogicMessage getFromIntent(android.content.Intent)\nclass FgsNewLogicMessage extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=false, genSetters=true, genToString=true, genAidl=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
