/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.app.cts.shortfgstesthelper;

import android.annotation.Nullable;
import android.content.ComponentName;
import android.os.Parcel;
import android.os.Parcelable;
import android.os.SystemClock;

import com.android.internal.util.DataClass;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * Message class used in this test.
 *
 * CHECKSTYLE:OFF Generated code
 * codegen $ANDROID_BUILD_TOP/cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java
 */
@DataClass(
        genConstructor = false,
        genSetters = true,
        genToString = true,
        genAidl = false)
public class ShortFgsMessage implements Parcelable {
    public ShortFgsMessage() {
        mTimestamp = SystemClock.uptimeMillis();
    }

    final private long mTimestamp;

    // if set, it's an "ack" messasge.
    private boolean ack;

    @Nullable
    private String mFailureString;

    private boolean mSetForeground;
    private int mFgsType;
    private int mStartCommandResult;
    private int mServiceStartId;
    @Nullable
    private ComponentName mComponentName;

    @Nullable
    private String mMethodName;

    /** If this is set, the receiver will call Service.startForeground() on mComponentName. */
    private boolean mDoCallStartForeground;

    /** If this is set, the receiver will call Service.stopForeground() on mComponentName. */
    private boolean mDoCallStopForeground;

    /** If this is set, the receiver will call Service.stopSelf() on mComponentName. */
    private boolean mDoCallStopSelf;

    /** If this is set, the helper process will kill itself. */
    private boolean mDoKillProcess;

    public void setException(Throwable e) {
        try (StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);) {
            e.printStackTrace(pw);

            mFailureString = "Exception detected: \n" + sw.toString();
        } catch (IOException ex) {
            throw new RuntimeException("Unexpected exception", ex);
        }
    }



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public long getTimestamp() {
        return mTimestamp;
    }

    @DataClass.Generated.Member
    public boolean isAck() {
        return ack;
    }

    @DataClass.Generated.Member
    public @Nullable String getFailureString() {
        return mFailureString;
    }

    @DataClass.Generated.Member
    public boolean isSetForeground() {
        return mSetForeground;
    }

    @DataClass.Generated.Member
    public int getFgsType() {
        return mFgsType;
    }

    @DataClass.Generated.Member
    public int getStartCommandResult() {
        return mStartCommandResult;
    }

    @DataClass.Generated.Member
    public int getServiceStartId() {
        return mServiceStartId;
    }

    @DataClass.Generated.Member
    public @Nullable ComponentName getComponentName() {
        return mComponentName;
    }

    @DataClass.Generated.Member
    public @Nullable String getMethodName() {
        return mMethodName;
    }

    /**
     * If this is set, the receiver will call Service.startForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStartForeground() {
        return mDoCallStartForeground;
    }

    /**
     * If this is set, the receiver will call Service.stopForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStopForeground() {
        return mDoCallStopForeground;
    }

    /**
     * If this is set, the receiver will call Service.stopSelf() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStopSelf() {
        return mDoCallStopSelf;
    }

    /**
     * If this is set, the helper process will kill itself.
     */
    @DataClass.Generated.Member
    public boolean isDoKillProcess() {
        return mDoKillProcess;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setAck( boolean value) {
        ack = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setFailureString(@android.annotation.NonNull String value) {
        mFailureString = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setSetForeground( boolean value) {
        mSetForeground = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setFgsType( int value) {
        mFgsType = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setStartCommandResult( int value) {
        mStartCommandResult = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setServiceStartId( int value) {
        mServiceStartId = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setComponentName(@android.annotation.NonNull ComponentName value) {
        mComponentName = value;
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setMethodName(@android.annotation.NonNull String value) {
        mMethodName = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.startForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setDoCallStartForeground( boolean value) {
        mDoCallStartForeground = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.stopForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setDoCallStopForeground( boolean value) {
        mDoCallStopForeground = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.stopSelf() on mComponentName.
     */
    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setDoCallStopSelf( boolean value) {
        mDoCallStopSelf = value;
        return this;
    }

    /**
     * If this is set, the helper process will kill itself.
     */
    @DataClass.Generated.Member
    public @android.annotation.NonNull ShortFgsMessage setDoKillProcess( boolean value) {
        mDoKillProcess = value;
        return this;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "ShortFgsMessage { " +
                "timestamp = " + mTimestamp + ", " +
                "ack = " + ack + ", " +
                "failureString = " + mFailureString + ", " +
                "setForeground = " + mSetForeground + ", " +
                "fgsType = " + mFgsType + ", " +
                "startCommandResult = " + mStartCommandResult + ", " +
                "serviceStartId = " + mServiceStartId + ", " +
                "componentName = " + mComponentName + ", " +
                "methodName = " + mMethodName + ", " +
                "doCallStartForeground = " + mDoCallStartForeground + ", " +
                "doCallStopForeground = " + mDoCallStopForeground + ", " +
                "doCallStopSelf = " + mDoCallStopSelf + ", " +
                "doKillProcess = " + mDoKillProcess +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@android.annotation.NonNull Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        int flg = 0;
        if (ack) flg |= 0x2;
        if (mSetForeground) flg |= 0x8;
        if (mDoCallStartForeground) flg |= 0x200;
        if (mDoCallStopForeground) flg |= 0x400;
        if (mDoCallStopSelf) flg |= 0x800;
        if (mDoKillProcess) flg |= 0x1000;
        if (mFailureString != null) flg |= 0x4;
        if (mComponentName != null) flg |= 0x80;
        if (mMethodName != null) flg |= 0x100;
        dest.writeInt(flg);
        dest.writeLong(mTimestamp);
        if (mFailureString != null) dest.writeString(mFailureString);
        dest.writeInt(mFgsType);
        dest.writeInt(mStartCommandResult);
        dest.writeInt(mServiceStartId);
        if (mComponentName != null) dest.writeTypedObject(mComponentName, flags);
        if (mMethodName != null) dest.writeString(mMethodName);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected ShortFgsMessage(@android.annotation.NonNull Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        int flg = in.readInt();
        boolean _ack = (flg & 0x2) != 0;
        boolean setForeground = (flg & 0x8) != 0;
        boolean doCallStartForeground = (flg & 0x200) != 0;
        boolean doCallStopForeground = (flg & 0x400) != 0;
        boolean doCallStopSelf = (flg & 0x800) != 0;
        boolean doKillProcess = (flg & 0x1000) != 0;
        long timestamp = in.readLong();
        String failureString = (flg & 0x4) == 0 ? null : in.readString();
        int fgsType = in.readInt();
        int startCommandResult = in.readInt();
        int serviceStartId = in.readInt();
        ComponentName componentName = (flg & 0x80) == 0 ? null : (ComponentName) in.readTypedObject(ComponentName.CREATOR);
        String methodName = (flg & 0x100) == 0 ? null : in.readString();

        this.mTimestamp = timestamp;
        this.ack = _ack;
        this.mFailureString = failureString;
        this.mSetForeground = setForeground;
        this.mFgsType = fgsType;
        this.mStartCommandResult = startCommandResult;
        this.mServiceStartId = serviceStartId;
        this.mComponentName = componentName;
        this.mMethodName = methodName;
        this.mDoCallStartForeground = doCallStartForeground;
        this.mDoCallStopForeground = doCallStopForeground;
        this.mDoCallStopSelf = doCallStopSelf;
        this.mDoKillProcess = doKillProcess;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @android.annotation.NonNull Parcelable.Creator<ShortFgsMessage> CREATOR
            = new Parcelable.Creator<ShortFgsMessage>() {
        @Override
        public ShortFgsMessage[] newArray(int size) {
            return new ShortFgsMessage[size];
        }

        @Override
        public ShortFgsMessage createFromParcel(@android.annotation.NonNull Parcel in) {
            return new ShortFgsMessage(in);
        }
    };

    @DataClass.Generated(
            time = 1670018200235L,
            codegenVersion = "1.0.23",
            sourceFile = "cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java",
            inputSignatures = "final private  long mTimestamp\nprivate  boolean ack\nprivate @android.annotation.Nullable java.lang.String mFailureString\nprivate  boolean mSetForeground\nprivate  int mFgsType\nprivate  int mStartCommandResult\nprivate  int mServiceStartId\nprivate @android.annotation.Nullable android.content.ComponentName mComponentName\nprivate @android.annotation.Nullable java.lang.String mMethodName\nprivate  boolean mDoCallStartForeground\nprivate  boolean mDoCallStopForeground\nprivate  boolean mDoCallStopSelf\nprivate  boolean mDoKillProcess\npublic  void setException(java.lang.Throwable)\nclass ShortFgsMessage extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=false, genSetters=true, genToString=true, genAidl=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
