/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.app.cts.shortfgstesthelper;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.content.ComponentName;
import android.os.Parcel;
import android.os.Parcelable;
import android.os.SystemClock;

import com.android.internal.util.DataClass;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * Message class used in this test.
 *
 * CHECKSTYLE:OFF Generated code
 * codegen $ANDROID_BUILD_TOP/cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java
 */
@DataClass(
        genConstructor = false,
        genSetters = true,
        genToString = true,
        genAidl = false)
public class ShortFgsMessage implements Parcelable {
    public ShortFgsMessage() {
        mTimestamp = SystemClock.uptimeMillis();
    }

    final private long mTimestamp;

    // if set, it's an "ack" messasge.
    private boolean ack;

    @Nullable
    private String mFailureString;

    private int mFgsType;
    private int mStartCommandResult;
    private int mServiceStartId;
    @Nullable
    private ComponentName mComponentName;

    @Nullable
    private String mMethodName;

    /** If this is set, the receiver will call Context.startForegroundService() on mComponentName.*/
    private boolean mDoCallStartForegroundService;

    /** If this is set, the receiver will call Service.startForeground() on mComponentName. */
    private boolean mDoCallStartForeground;

    /** If this is set, the receiver will call Service.stopForeground() on mComponentName. */
    private boolean mDoCallStopForeground;

    /** If this is set, the receiver will call Service.stopSelf() on mComponentName. */
    private boolean mDoCallStopSelf;

    /** If this is set, the helper process will kill itself. */
    private boolean mDoKillProcess;

    /** If this is set, the receiver will start MyActivity. */
    private boolean mDoStartActivity;

    /** If this is set, the receiver will finish MyActivity. */
    private boolean mDoFinishActivity;

    /**
     * Send by the helper app to the main test package, via CallProvider, to get the
     * currently running test information.
     */
    private boolean mCallGetTestInfo;

    /** Class name of an exception we expect in ShortFgsMessageReceiver */
    @Nullable
    private String mExpectedExceptionClass;

    @Nullable
    private String mActualExceptionClasss;

    @Nullable
    private String mActualExceptionMessage;

    private long mLastTestStartUptime;
    private long mLastTestEndUptime;

    @NonNull
    public ShortFgsMessage setExpectedExceptionClass(Class<?> clazz) {
        mExpectedExceptionClass = clazz.getName();
        return this;
    }

    @Nullable
    public Class<?> getExpectedExceptionClass() throws ClassNotFoundException {
        if (mExpectedExceptionClass == null) {
            return null;
        }
        return Class.forName(mExpectedExceptionClass);
    }

    public void setException(Throwable e) {
        mActualExceptionClasss = e.getClass().getName();
        mActualExceptionMessage = e.getMessage();

        try (StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);) {
            e.printStackTrace(pw);

            mFailureString = "Exception detected: \n" + sw.toString();
        } catch (IOException ex) {
            throw new RuntimeException("Unexpected exception", ex);
        }
    }



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public long getTimestamp() {
        return mTimestamp;
    }

    @DataClass.Generated.Member
    public boolean isAck() {
        return ack;
    }

    @DataClass.Generated.Member
    public @Nullable String getFailureString() {
        return mFailureString;
    }

    @DataClass.Generated.Member
    public int getFgsType() {
        return mFgsType;
    }

    @DataClass.Generated.Member
    public int getStartCommandResult() {
        return mStartCommandResult;
    }

    @DataClass.Generated.Member
    public int getServiceStartId() {
        return mServiceStartId;
    }

    @DataClass.Generated.Member
    public @Nullable ComponentName getComponentName() {
        return mComponentName;
    }

    @DataClass.Generated.Member
    public @Nullable String getMethodName() {
        return mMethodName;
    }

    /**
     * If this is set, the receiver will call Context.startForegroundService() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStartForegroundService() {
        return mDoCallStartForegroundService;
    }

    /**
     * If this is set, the receiver will call Service.startForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStartForeground() {
        return mDoCallStartForeground;
    }

    /**
     * If this is set, the receiver will call Service.stopForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStopForeground() {
        return mDoCallStopForeground;
    }

    /**
     * If this is set, the receiver will call Service.stopSelf() on mComponentName.
     */
    @DataClass.Generated.Member
    public boolean isDoCallStopSelf() {
        return mDoCallStopSelf;
    }

    /**
     * If this is set, the helper process will kill itself.
     */
    @DataClass.Generated.Member
    public boolean isDoKillProcess() {
        return mDoKillProcess;
    }

    /**
     * If this is set, the receiver will start MyActivity.
     */
    @DataClass.Generated.Member
    public boolean isDoStartActivity() {
        return mDoStartActivity;
    }

    /**
     * If this is set, the receiver will finish MyActivity.
     */
    @DataClass.Generated.Member
    public boolean isDoFinishActivity() {
        return mDoFinishActivity;
    }

    /**
     * Send by the helper app to the main test package, via CallProvider, to get the
     * currently running test information.
     */
    @DataClass.Generated.Member
    public boolean isCallGetTestInfo() {
        return mCallGetTestInfo;
    }

    @DataClass.Generated.Member
    public @Nullable String getActualExceptionClasss() {
        return mActualExceptionClasss;
    }

    @DataClass.Generated.Member
    public @Nullable String getActualExceptionMessage() {
        return mActualExceptionMessage;
    }

    @DataClass.Generated.Member
    public long getLastTestStartUptime() {
        return mLastTestStartUptime;
    }

    @DataClass.Generated.Member
    public long getLastTestEndUptime() {
        return mLastTestEndUptime;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setAck( boolean value) {
        ack = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setFailureString(@NonNull String value) {
        mFailureString = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setFgsType( int value) {
        mFgsType = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setStartCommandResult( int value) {
        mStartCommandResult = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setServiceStartId( int value) {
        mServiceStartId = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setComponentName(@NonNull ComponentName value) {
        mComponentName = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setMethodName(@NonNull String value) {
        mMethodName = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Context.startForegroundService() on mComponentName.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoCallStartForegroundService( boolean value) {
        mDoCallStartForegroundService = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.startForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoCallStartForeground( boolean value) {
        mDoCallStartForeground = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.stopForeground() on mComponentName.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoCallStopForeground( boolean value) {
        mDoCallStopForeground = value;
        return this;
    }

    /**
     * If this is set, the receiver will call Service.stopSelf() on mComponentName.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoCallStopSelf( boolean value) {
        mDoCallStopSelf = value;
        return this;
    }

    /**
     * If this is set, the helper process will kill itself.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoKillProcess( boolean value) {
        mDoKillProcess = value;
        return this;
    }

    /**
     * If this is set, the receiver will start MyActivity.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoStartActivity( boolean value) {
        mDoStartActivity = value;
        return this;
    }

    /**
     * If this is set, the receiver will finish MyActivity.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setDoFinishActivity( boolean value) {
        mDoFinishActivity = value;
        return this;
    }

    /**
     * Send by the helper app to the main test package, via CallProvider, to get the
     * currently running test information.
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setCallGetTestInfo( boolean value) {
        mCallGetTestInfo = value;
        return this;
    }

    /**
     * Class name of an exception we expect in ShortFgsMessageReceiver
     */
    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setExpectedExceptionClass(@NonNull String value) {
        mExpectedExceptionClass = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setActualExceptionClasss(@NonNull String value) {
        mActualExceptionClasss = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setActualExceptionMessage(@NonNull String value) {
        mActualExceptionMessage = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setLastTestStartUptime( long value) {
        mLastTestStartUptime = value;
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ShortFgsMessage setLastTestEndUptime( long value) {
        mLastTestEndUptime = value;
        return this;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "ShortFgsMessage { " +
                "timestamp = " + mTimestamp + ", " +
                "ack = " + ack + ", " +
                "failureString = " + mFailureString + ", " +
                "fgsType = " + mFgsType + ", " +
                "startCommandResult = " + mStartCommandResult + ", " +
                "serviceStartId = " + mServiceStartId + ", " +
                "componentName = " + mComponentName + ", " +
                "methodName = " + mMethodName + ", " +
                "doCallStartForegroundService = " + mDoCallStartForegroundService + ", " +
                "doCallStartForeground = " + mDoCallStartForeground + ", " +
                "doCallStopForeground = " + mDoCallStopForeground + ", " +
                "doCallStopSelf = " + mDoCallStopSelf + ", " +
                "doKillProcess = " + mDoKillProcess + ", " +
                "doStartActivity = " + mDoStartActivity + ", " +
                "doFinishActivity = " + mDoFinishActivity + ", " +
                "callGetTestInfo = " + mCallGetTestInfo + ", " +
                "expectedExceptionClass = " + mExpectedExceptionClass + ", " +
                "actualExceptionClasss = " + mActualExceptionClasss + ", " +
                "actualExceptionMessage = " + mActualExceptionMessage + ", " +
                "lastTestStartUptime = " + mLastTestStartUptime + ", " +
                "lastTestEndUptime = " + mLastTestEndUptime +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        long flg = 0;
        if (ack) flg |= 0x2;
        if (mDoCallStartForegroundService) flg |= 0x100;
        if (mDoCallStartForeground) flg |= 0x200;
        if (mDoCallStopForeground) flg |= 0x400;
        if (mDoCallStopSelf) flg |= 0x800;
        if (mDoKillProcess) flg |= 0x1000;
        if (mDoStartActivity) flg |= 0x2000;
        if (mDoFinishActivity) flg |= 0x4000;
        if (mCallGetTestInfo) flg |= 0x8000;
        if (mFailureString != null) flg |= 0x4;
        if (mComponentName != null) flg |= 0x40;
        if (mMethodName != null) flg |= 0x80;
        if (mExpectedExceptionClass != null) flg |= 0x10000;
        if (mActualExceptionClasss != null) flg |= 0x20000;
        if (mActualExceptionMessage != null) flg |= 0x40000;
        dest.writeLong(flg);
        dest.writeLong(mTimestamp);
        if (mFailureString != null) dest.writeString(mFailureString);
        dest.writeInt(mFgsType);
        dest.writeInt(mStartCommandResult);
        dest.writeInt(mServiceStartId);
        if (mComponentName != null) dest.writeTypedObject(mComponentName, flags);
        if (mMethodName != null) dest.writeString(mMethodName);
        if (mExpectedExceptionClass != null) dest.writeString(mExpectedExceptionClass);
        if (mActualExceptionClasss != null) dest.writeString(mActualExceptionClasss);
        if (mActualExceptionMessage != null) dest.writeString(mActualExceptionMessage);
        dest.writeLong(mLastTestStartUptime);
        dest.writeLong(mLastTestEndUptime);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected ShortFgsMessage(@NonNull Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        long flg = in.readLong();
        boolean _ack = (flg & 0x2) != 0;
        boolean doCallStartForegroundService = (flg & 0x100) != 0;
        boolean doCallStartForeground = (flg & 0x200) != 0;
        boolean doCallStopForeground = (flg & 0x400) != 0;
        boolean doCallStopSelf = (flg & 0x800) != 0;
        boolean doKillProcess = (flg & 0x1000) != 0;
        boolean doStartActivity = (flg & 0x2000) != 0;
        boolean doFinishActivity = (flg & 0x4000) != 0;
        boolean callGetTestInfo = (flg & 0x8000) != 0;
        long timestamp = in.readLong();
        String failureString = (flg & 0x4) == 0 ? null : in.readString();
        int fgsType = in.readInt();
        int startCommandResult = in.readInt();
        int serviceStartId = in.readInt();
        ComponentName componentName = (flg & 0x40) == 0 ? null : (ComponentName) in.readTypedObject(ComponentName.CREATOR);
        String methodName = (flg & 0x80) == 0 ? null : in.readString();
        String expectedExceptionClass = (flg & 0x10000) == 0 ? null : in.readString();
        String actualExceptionClasss = (flg & 0x20000) == 0 ? null : in.readString();
        String actualExceptionMessage = (flg & 0x40000) == 0 ? null : in.readString();
        long lastTestStartUptime = in.readLong();
        long lastTestEndUptime = in.readLong();

        this.mTimestamp = timestamp;
        this.ack = _ack;
        this.mFailureString = failureString;
        this.mFgsType = fgsType;
        this.mStartCommandResult = startCommandResult;
        this.mServiceStartId = serviceStartId;
        this.mComponentName = componentName;
        this.mMethodName = methodName;
        this.mDoCallStartForegroundService = doCallStartForegroundService;
        this.mDoCallStartForeground = doCallStartForeground;
        this.mDoCallStopForeground = doCallStopForeground;
        this.mDoCallStopSelf = doCallStopSelf;
        this.mDoKillProcess = doKillProcess;
        this.mDoStartActivity = doStartActivity;
        this.mDoFinishActivity = doFinishActivity;
        this.mCallGetTestInfo = callGetTestInfo;
        this.mExpectedExceptionClass = expectedExceptionClass;
        this.mActualExceptionClasss = actualExceptionClasss;
        this.mActualExceptionMessage = actualExceptionMessage;
        this.mLastTestStartUptime = lastTestStartUptime;
        this.mLastTestEndUptime = lastTestEndUptime;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ShortFgsMessage> CREATOR
            = new Parcelable.Creator<ShortFgsMessage>() {
        @Override
        public ShortFgsMessage[] newArray(int size) {
            return new ShortFgsMessage[size];
        }

        @Override
        public ShortFgsMessage createFromParcel(@NonNull Parcel in) {
            return new ShortFgsMessage(in);
        }
    };

    @DataClass.Generated(
            time = 1670538953028L,
            codegenVersion = "1.0.23",
            sourceFile = "cts/tests/app/ShortFgsTest/ShortFgsTestHelper/src/android/app/cts/shortfgstesthelper/ShortFgsMessage.java",
            inputSignatures = "final private  long mTimestamp\nprivate  boolean ack\nprivate @android.annotation.Nullable java.lang.String mFailureString\nprivate  int mFgsType\nprivate  int mStartCommandResult\nprivate  int mServiceStartId\nprivate @android.annotation.Nullable android.content.ComponentName mComponentName\nprivate @android.annotation.Nullable java.lang.String mMethodName\nprivate  boolean mDoCallStartForegroundService\nprivate  boolean mDoCallStartForeground\nprivate  boolean mDoCallStopForeground\nprivate  boolean mDoCallStopSelf\nprivate  boolean mDoKillProcess\nprivate  boolean mDoStartActivity\nprivate  boolean mDoFinishActivity\nprivate  boolean mCallGetTestInfo\nprivate @android.annotation.Nullable java.lang.String mExpectedExceptionClass\nprivate @android.annotation.Nullable java.lang.String mActualExceptionClasss\nprivate @android.annotation.Nullable java.lang.String mActualExceptionMessage\nprivate  long mLastTestStartUptime\nprivate  long mLastTestEndUptime\npublic @android.annotation.NonNull android.app.cts.shortfgstesthelper.ShortFgsMessage setExpectedExceptionClass(java.lang.Class<?>)\npublic @android.annotation.Nullable java.lang.Class<?> getExpectedExceptionClass()\npublic  void setException(java.lang.Throwable)\nclass ShortFgsMessage extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=false, genSetters=true, genToString=true, genAidl=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
