#!/bin/bash

# Helper script for running CTS tests with all the right params.
# Example usage:
#  run-test <package_name>  // To run all the tests in a package.
#  run-test <package_name>.<class_name>  // To run all the tests in a class.
#  run-test <package_name>.<class_name>#<method_name>  // To run a specific test in a class.

echo " "
echo "Running test...$1"
echo " "
cts-tradefed run commandAndExit cts-dev --module CtsServicesHostTestCases --test $1 --disable-reboot --skip-device-info --skip-all-system-status-check --skip-preconditions
