/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.os.cts.process.common;

import android.annotation.Nullable;
import android.os.Parcelable;

import com.android.internal.util.DataClass;

/**
 * codegen ${ANDROID_BUILD_TOP}/cts/tests/process/src/android/os/cts/process/common/Message.java
 */
@DataClass(
        genConstructor = false,
        genSetters = false,
        genToString = true,
        genAidl = false)
public class Message implements Parcelable {
    public Message() {
    }

    @Nullable
    public String processName;
    public long startElapsedRealtime;
    public long startUptimeMillis;
    public long startRequestedElapsedRealtime;
    public long startRequestedUptimeMillis;
    public long nowElapsedRealtime;
    public long nowUptimeMillis;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/cts/tests/process/src/android/os/cts/process/common/Message.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "Message { " +
                "processName = " + processName + ", " +
                "startElapsedRealtime = " + startElapsedRealtime + ", " +
                "startUptimeMillis = " + startUptimeMillis + ", " +
                "startRequestedElapsedRealtime = " + startRequestedElapsedRealtime + ", " +
                "startRequestedUptimeMillis = " + startRequestedUptimeMillis + ", " +
                "nowElapsedRealtime = " + nowElapsedRealtime + ", " +
                "nowUptimeMillis = " + nowUptimeMillis +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@android.annotation.NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (processName != null) flg |= 0x1;
        dest.writeByte(flg);
        if (processName != null) dest.writeString(processName);
        dest.writeLong(startElapsedRealtime);
        dest.writeLong(startUptimeMillis);
        dest.writeLong(startRequestedElapsedRealtime);
        dest.writeLong(startRequestedUptimeMillis);
        dest.writeLong(nowElapsedRealtime);
        dest.writeLong(nowUptimeMillis);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected Message(@android.annotation.NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        String _processName = (flg & 0x1) == 0 ? null : in.readString();
        long _startElapsedRealtime = in.readLong();
        long _startUptimeMillis = in.readLong();
        long _startRequestedElapsedRealtime = in.readLong();
        long _startRequestedUptimeMillis = in.readLong();
        long _nowElapsedRealtime = in.readLong();
        long _nowUptimeMillis = in.readLong();

        this.processName = _processName;
        this.startElapsedRealtime = _startElapsedRealtime;
        this.startUptimeMillis = _startUptimeMillis;
        this.startRequestedElapsedRealtime = _startRequestedElapsedRealtime;
        this.startRequestedUptimeMillis = _startRequestedUptimeMillis;
        this.nowElapsedRealtime = _nowElapsedRealtime;
        this.nowUptimeMillis = _nowUptimeMillis;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @android.annotation.NonNull Parcelable.Creator<Message> CREATOR
            = new Parcelable.Creator<Message>() {
        @Override
        public Message[] newArray(int size) {
            return new Message[size];
        }

        @Override
        public Message createFromParcel(@android.annotation.NonNull android.os.Parcel in) {
            return new Message(in);
        }
    };

    @DataClass.Generated(
            time = 1636764125263L,
            codegenVersion = "1.0.23",
            sourceFile = "cts/tests/process/src/android/os/cts/process/common/Message.java",
            inputSignatures = "public @android.annotation.Nullable java.lang.String processName\npublic  long startElapsedRealtime\npublic  long startUptimeMillis\npublic  long startRequestedElapsedRealtime\npublic  long startRequestedUptimeMillis\npublic  long nowElapsedRealtime\npublic  long nowUptimeMillis\nclass Message extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=false, genSetters=false, genToString=true, genAidl=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
